/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Futures and Options market data client */
export declare class FutOptClient {
  /** Get intraday client for real-time futures/options data */
  get intraday(): FutOptIntradayClient
}

/** FutOpt intraday data client */
export declare class FutOptIntradayClient {
  /**
   * Get intraday quote for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4" for TX futures, "TXO18000C4" for options)
   * @returns Promise resolving to Quote object with current price and volume data
   *
   * @example
   * ```javascript
   * const client = new RestClient('your-api-key');
   * const quote = await client.futopt.intraday.quote('TXFC4');
   * console.log(quote.lastPrice);  // 17550.0
   * console.log(quote.symbol);     // "TXFC4"
   * ```
   */
  quote(symbol: string): Promise<any>
  /**
   * Get intraday ticker for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4")
   * @returns Promise resolving to Ticker object with last trade info
   */
  ticker(symbol: string): Promise<any>
  /**
   * Get intraday candles for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4")
   * @param timeframe - Candle timeframe: "1", "5", "10", "15", "30", "60" (minutes)
   * @returns Promise resolving to Candles response with OHLCV data
   */
  candles(symbol: string, timeframe: string): Promise<any>
  /**
   * Get intraday trades for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4")
   * @returns Promise resolving to Trades response with recent trade history
   */
  trades(symbol: string): Promise<any>
  /**
   * Get intraday volumes for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4")
   * @returns Promise resolving to Volumes response with volume at each price level
   */
  volumes(symbol: string): Promise<any>
  /**
   * Get product list for futures/options
   *
   * @param typ - Type: "FUTURE" or "OPTION" (required)
   * @param contractType - Contract type filter (optional): "I" (index), "R" (rate), "B" (bond), "C" (currency), "S" (stock), "E" (ETF)
   * @returns Promise resolving to Products response with available contracts
   */
  products(typ: string, contractType?: string | undefined | null): Promise<any>
}

/**
 * FutOpt WebSocket client for real-time futures/options market data
 *
 * # JavaScript Usage
 *
 * ```javascript
 * // Event handlers
 * ws.futopt.on('message', (data) => {
 *   const msg = JSON.parse(data);
 *   console.log(msg);
 * });
 * ws.futopt.on('connect', () => console.log('FutOpt WebSocket connected'));
 *
 * // Connect
 * ws.futopt.connect();
 *
 * // Subscribe to channels
 * ws.futopt.subscribe({ channel: 'trades', symbol: 'TXFC4' });
 * ws.futopt.subscribe({ channel: 'books', symbol: 'MXFB4', afterHours: true });
 * ```
 */
export declare class FutOptWebSocketClient {
  /**
   * Register an event handler
   *
   * @param event - Event type: "message", "connect", "disconnect", "reconnect", "error"
   * @param callback - JavaScript callback function receiving string data
   */
  on(event: string, callback: ((err: Error | null, arg: string) => any)): void
  /**
   * Connect to the FutOpt WebSocket server
   *
   * This method spawns a background thread that manages the WebSocket connection.
   * Connection result will be delivered via 'connect' or 'error' callbacks.
   */
  connect(): void
  /**
   * Subscribe to a channel
   *
   * @param options - Subscription options: { channel: string, symbol: string, afterHours?: boolean }
   */
  subscribe(options: any): void
  /**
   * Unsubscribe from a channel by subscription ID
   *
   * @param subscriptionId - The subscription ID returned from subscribed event
   */
  unsubscribe(subscriptionId: string): void
  /** Disconnect from the WebSocket server */
  disconnect(): void
  /** Check if connected */
  get isConnected(): boolean
  /**
   * Check if client has been closed
   *
   * Returns true if disconnect() has been called and client is closed.
   * Once closed, the client cannot be reused - create a new instance.
   */
  get isClosed(): boolean
}

/**
 * REST client for Fugle market data API (JavaScript wrapper)
 *
 * # JavaScript Usage
 *
 * ```javascript
 * const { RestClient } = require('@fubon/marketdata-js');
 *
 * // Create client with API key
 * const client = new RestClient('your-api-key');
 *
 * // Access stock market data
 * const quote = client.stock.intraday.quote('2330');
 * console.log(quote.lastPrice, quote.symbol);
 *
 * // Access futures/options market data
 * const futoptQuote = client.futopt.intraday.quote('TXFC4');
 * console.log(futoptQuote.lastPrice, futoptQuote.symbol);
 * ```
 */
export declare class RestClient {
  /**
   * Create a new REST client with API key authentication
   *
   * @param apiKey - Your Fugle API key
   */
  constructor(apiKey: string)
  /** Get the stock client for accessing stock market data */
  get stock(): StockClient
  /** Get the FutOpt client for accessing futures/options market data */
  get futopt(): FutOptClient
}

/** Stock market data client */
export declare class StockClient {
  /** Get intraday client for real-time stock data */
  get intraday(): StockIntradayClient
}

/** Stock intraday data client */
export declare class StockIntradayClient {
  /**
   * Get intraday quote for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @returns Promise resolving to Quote object with current price and volume data
   *
   * @example
   * ```javascript
   * const client = new RestClient('your-api-key');
   * const quote = await client.stock.intraday.quote('2330');
   * console.log(quote.lastPrice);  // 580.0
   * console.log(quote.symbol);     // "2330"
   * console.log(quote.bids);       // [{price: 579.0, size: 100}, ...]
   * ```
   */
  quote(symbol: string): Promise<any>
  /**
   * Get intraday ticker for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @returns Promise resolving to Ticker object with last trade info
   */
  ticker(symbol: string): Promise<any>
  /**
   * Get intraday candles for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @param timeframe - Candle timeframe: "1", "5", "10", "15", "30", "60" (minutes)
   * @returns Promise resolving to Candles response with OHLCV data
   */
  candles(symbol: string, timeframe: string): Promise<any>
  /**
   * Get intraday trades for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @returns Promise resolving to Trades response with recent trade history
   */
  trades(symbol: string): Promise<any>
  /**
   * Get intraday volumes for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @returns Promise resolving to Volumes response with volume at each price level
   */
  volumes(symbol: string): Promise<any>
}

/**
 * Stock WebSocket client for real-time stock market data
 *
 * # JavaScript Usage
 *
 * ```javascript
 * // Event handlers
 * ws.stock.on('message', (data) => {
 *   const msg = JSON.parse(data);
 *   console.log(msg);
 * });
 * ws.stock.on('connect', () => console.log('Stock WebSocket connected'));
 * ws.stock.on('disconnect', (reason) => console.log('Disconnected:', reason));
 * ws.stock.on('reconnect', (info) => console.log('Reconnecting:', info));
 * ws.stock.on('error', (err) => console.error('Error:', err));
 *
 * // Connect
 * ws.stock.connect();
 *
 * // Subscribe to channels
 * ws.stock.subscribe({ channel: 'trades', symbol: '2330' });
 * ws.stock.subscribe({ channel: 'candles', symbol: '2330' });
 * ```
 */
export declare class StockWebSocketClient {
  /**
   * Register an event handler
   *
   * @param event - Event type: "message", "connect", "disconnect", "reconnect", "error"
   * @param callback - JavaScript callback function receiving string data
   *
   * @example
   * ```javascript
   * ws.stock.on('message', (data) => console.log(data));
   * ws.stock.on('connect', () => console.log('Connected'));
   * ws.stock.on('error', (err) => console.error(err));
   * ```
   */
  on(event: string, callback: ((err: Error | null, arg: string) => any)): void
  /**
   * Connect to the stock WebSocket server
   *
   * This method spawns a background thread that manages the WebSocket connection.
   * Connection result will be delivered via 'connect' or 'error' callbacks.
   */
  connect(): void
  /**
   * Subscribe to a channel
   *
   * @param options - Subscription options: { channel: string, symbol: string, intradayOddLot?: boolean }
   */
  subscribe(options: any): void
  /**
   * Unsubscribe from a channel by subscription ID
   *
   * @param subscriptionId - The subscription ID returned from subscribed event
   */
  unsubscribe(subscriptionId: string): void
  /** Disconnect from the WebSocket server */
  disconnect(): void
  /** Check if connected */
  get isConnected(): boolean
  /**
   * Check if client has been closed
   *
   * Returns true if disconnect() has been called and client is closed.
   * Once closed, the client cannot be reused - create a new instance.
   */
  get isClosed(): boolean
}

/**
 * WebSocket client for real-time market data (JavaScript wrapper)
 *
 * # JavaScript Usage
 *
 * ```javascript
 * const { WebSocketClient } = require('@fubon/marketdata-js');
 *
 * // Create client with API key
 * const ws = new WebSocketClient('your-api-key');
 *
 * // Register event handlers for stock data
 * ws.stock.on('message', (data) => console.log(JSON.parse(data)));
 * ws.stock.on('connect', () => console.log('Connected!'));
 * ws.stock.on('error', (err) => console.error(err));
 *
 * // Connect and subscribe
 * ws.stock.connect();
 * ws.stock.subscribe({ channel: 'trades', symbol: '2330' });
 * ```
 */
export declare class WebSocketClient {
  /**
   * Create a new WebSocket client with API key authentication
   *
   * @param apiKey - Your Fugle API key
   */
  constructor(apiKey: string)
  /** Get the stock WebSocket client for real-time stock data */
  get stock(): StockWebSocketClient
  /** Get the FutOpt WebSocket client for real-time futures/options data */
  get futopt(): FutOptWebSocketClient
}
