/* auto-generated by NAPI-RS */
/* eslint-disable */

// ============================================================================
// Common Types
// ============================================================================

/** Price level for order book (bid/ask) */
export interface PriceLevel {
  /** Price at this level */
  price: number;
  /** Size (volume) at this level */
  size: number;
}

/** Trade execution info */
export interface TradeInfo {
  /** Best bid price at trade time */
  bid?: number;
  /** Best ask price at trade time */
  ask?: number;
  /** Trade price */
  price: number;
  /** Trade size */
  size: number;
  /** Trade timestamp (Unix milliseconds) */
  time: number;
}

/** Total trading statistics */
export interface TotalStats {
  /** Total trade value */
  tradeValue: number;
  /** Total trade volume */
  tradeVolume: number;
  /** Volume traded at bid */
  tradeVolumeAtBid?: number;
  /** Volume traded at ask */
  tradeVolumeAtAsk?: number;
  /** Number of transactions */
  transaction?: number;
  /** Timestamp */
  time?: number;
}

/** Trading halt status */
export interface TradingHalt {
  /** Whether trading is halted */
  isHalted: boolean;
  /** Halt timestamp */
  time?: number;
}

// ============================================================================
// REST Response Types - Stock/FutOpt Intraday
// ============================================================================

/**
 * Quote response from intraday/quote/{symbol}
 *
 * Contains real-time price, volume, and order book data.
 */
export interface QuoteResponse {
  /** Trading date (YYYY-MM-DD) */
  date: string;
  /** Security type (e.g., "EQUITY", "ODDLOT") */
  type?: string;
  /** Exchange code (e.g., "TWSE", "TPEx", "TAIFEX") */
  exchange?: string;
  /** Market (e.g., "TSE", "OTC") */
  market?: string;
  /** Symbol (e.g., "2330" for stock, "TXFC4" for futures) */
  symbol: string;
  /** Security name */
  name?: string;

  // OHLC prices with timestamps
  /** Open price */
  openPrice?: number;
  /** Open time (Unix milliseconds) */
  openTime?: number;
  /** High price */
  highPrice?: number;
  /** High time (Unix milliseconds) */
  highTime?: number;
  /** Low price */
  lowPrice?: number;
  /** Low time (Unix milliseconds) */
  lowTime?: number;
  /** Close price */
  closePrice?: number;
  /** Close time (Unix milliseconds) */
  closeTime?: number;

  // Current trading info
  /** Last traded price */
  lastPrice?: number;
  /** Last traded size */
  lastSize?: number;
  /** Average price */
  avgPrice?: number;
  /** Price change from previous close */
  change?: number;
  /** Percentage change from previous close */
  changePercent?: number;
  /** Price amplitude */
  amplitude?: number;

  // Order book
  /** Bid price levels */
  bids: PriceLevel[];
  /** Ask price levels */
  asks: PriceLevel[];

  // Aggregated stats
  /** Total trading statistics */
  total?: TotalStats;
  /** Last trade info */
  lastTrade?: TradeInfo;
  /** Last trial (simulated matching) info */
  lastTrial?: TradeInfo;
  /** Trading halt status */
  tradingHalt?: TradingHalt;

  // Limit price flags
  /** Is at limit down price */
  isLimitDownPrice: boolean;
  /** Is at limit up price */
  isLimitUpPrice: boolean;
  /** Is limit down bid */
  isLimitDownBid: boolean;
  /** Is limit up bid */
  isLimitUpBid: boolean;
  /** Is limit down ask */
  isLimitDownAsk: boolean;
  /** Is limit up ask */
  isLimitUpAsk: boolean;
  /** Is limit down halt */
  isLimitDownHalt: boolean;
  /** Is limit up halt */
  isLimitUpHalt: boolean;

  // Trading session flags
  /** Is in trial (simulated matching) period */
  isTrial: boolean;
  /** Is delayed open */
  isDelayedOpen: boolean;
  /** Is delayed close */
  isDelayedClose: boolean;
  /** Is continuous trading */
  isContinuous: boolean;
  /** Is market open */
  isOpen: boolean;
  /** Is market closed */
  isClose: boolean;

  /** Last updated timestamp (Unix milliseconds) */
  lastUpdated?: number;
}

/**
 * Ticker response from intraday/ticker/{symbol}
 *
 * Contains static security information and trading rules.
 */
export interface TickerResponse {
  /** Trading date (YYYY-MM-DD) */
  date: string;
  /** Security type (e.g., "EQUITY", "ODDLOT") */
  type?: string;
  /** Exchange code */
  exchange?: string;
  /** Market */
  market?: string;
  /** Symbol */
  symbol: string;

  // Stock info
  /** Stock name (Chinese) */
  name?: string;
  /** Stock name (English) */
  nameEn?: string;
  /** Industry category */
  industry?: string;
  /** Security type classification */
  securityType?: string;

  // Price limits
  /** Reference price (previous close) */
  referencePrice?: number;
  /** Limit up price */
  limitUpPrice?: number;
  /** Limit down price */
  limitDownPrice?: number;
  /** Previous close price */
  previousClose?: number;

  // Trading rules
  /** Can day trade */
  canDayTrade: boolean;
  /** Can buy day trade */
  canBuyDayTrade: boolean;
  /** Can below flat margin short sell */
  canBelowFlatMarginShortSell: boolean;
  /** Can below flat SBL short sell */
  canBelowFlatSBLShortSell: boolean;

  // Attention flags
  /** Is attention stock */
  isAttention: boolean;
  /** Is disposition stock */
  isDisposition: boolean;
  /** Is unusually recommended */
  isUnusuallyRecommended: boolean;
  /** Is specific abnormally */
  isSpecificAbnormally: boolean;
  /** Is newly compiled */
  isNewlyCompiled: boolean;

  // Trading parameters
  /** Matching interval (seconds) */
  matchingInterval?: number;
  /** Security status */
  securityStatus?: string;
  /** Board lot size */
  boardLot?: number;
  /** Trading currency */
  tradingCurrency?: string;

  // Warrant/ETN specific
  /** Exercise price */
  exercisePrice?: number;
  /** Exercised volume */
  exercisedVolume?: number;
  /** Cancelled volume */
  cancelledVolume?: number;
  /** Remaining volume */
  remainingVolume?: number;
  /** Exercise ratio */
  exerciseRatio?: number;
  /** Cap price */
  capPrice?: number;
  /** Floor price */
  floorPrice?: number;
  /** Maturity date */
  maturityDate?: string;

  // Session times
  /** Open time */
  openTime?: string;
  /** Close time */
  closeTime?: string;
}

/** A single intraday candlestick bar */
export interface IntradayCandle {
  /** Open price */
  open: number;
  /** High price */
  high: number;
  /** Low price */
  low: number;
  /** Close price */
  close: number;
  /** Volume */
  volume: number;
  /** Average price (VWAP for the candle period) */
  average?: number;
  /** Candle timestamp (Unix milliseconds) */
  time: number;
}

/**
 * Candles response from intraday/candles/{symbol}
 *
 * Contains OHLCV candlestick data.
 */
export interface CandlesResponse {
  /** Trading date (YYYY-MM-DD) */
  date: string;
  /** Security type */
  type?: string;
  /** Exchange code */
  exchange?: string;
  /** Market */
  market?: string;
  /** Symbol */
  symbol: string;
  /** Timeframe (e.g., "1", "5", "10", "15", "30", "60") */
  timeframe?: string;
  /** Candle data */
  data: IntradayCandle[];
}

/** A single trade execution */
export interface Trade {
  /** Best bid price at trade time */
  bid?: number;
  /** Best ask price at trade time */
  ask?: number;
  /** Trade price */
  price: number;
  /** Trade size (volume) */
  size: number;
  /** Trade timestamp (Unix milliseconds) */
  time: number;
}

/**
 * Trades response from intraday/trades/{symbol}
 *
 * Contains recent trade executions.
 */
export interface TradesResponse {
  /** Trading date (YYYY-MM-DD) */
  date: string;
  /** Security type */
  type?: string;
  /** Exchange code */
  exchange?: string;
  /** Market */
  market?: string;
  /** Symbol */
  symbol: string;
  /** Trade data */
  data: Trade[];
}

/** Volume at a specific price level */
export interface VolumeAtPrice {
  /** Price level */
  price: number;
  /** Total volume at this price */
  volume: number;
  /** Volume traded at bid */
  volumeAtBid?: number;
  /** Volume traded at ask */
  volumeAtAsk?: number;
}

/**
 * Volumes response from intraday/volumes/{symbol}
 *
 * Contains volume profile data at each price level.
 */
export interface VolumesResponse {
  /** Trading date (YYYY-MM-DD) */
  date: string;
  /** Security type */
  type?: string;
  /** Exchange code */
  exchange?: string;
  /** Market */
  market?: string;
  /** Symbol */
  symbol: string;
  /** Volume data at each price level */
  data: VolumeAtPrice[];
}

// ============================================================================
// REST Response Types - FutOpt Specific
// ============================================================================

/** Contract type for futures/options */
export type ContractType = 'I' | 'R' | 'B' | 'C' | 'S' | 'E';

/** FutOpt type */
export type FutOptType = 'FUTURE' | 'OPTION';

/** A single product entry in FutOpt products response */
export interface FutOptProduct {
  /** Product type (FUTURE/OPTION) */
  type: string;
  /** Exchange code */
  exchange: string;
  /** Contract symbol */
  symbol: string;
  /** Contract name */
  name: string;
  /** Underlying symbol */
  underlyingSymbol: string;
  /** Contract type */
  contractType: string;
  /** Contract size */
  contractSize: number;
  /** Status code */
  statusCode: string;
  /** Trading currency */
  tradingCurrency: string;
  /** Whether quote is acceptable */
  quoteAcceptable: boolean;
  /** Start date */
  startDate: string;
  /** Whether block trade is allowed */
  canBlockTrade: boolean;
  /** Expiry type */
  expiryType: string;
  /** Underlying type */
  underlyingType: string;
  /** Market close group */
  marketCloseGroup: number;
  /** End session */
  endSession: number;
}

/**
 * Products response from futopt/intraday/products
 *
 * Contains available futures/options contracts.
 */
export interface ProductsResponse {
  /** Trading date (YYYY-MM-DD) */
  date: string;
  /** Product type */
  type: string;
  /** Trading session */
  session: string;
  /** Contract type filter applied */
  contractType: string;
  /** Status filter applied */
  status: string;
  /** Product list */
  data: FutOptProduct[];
}

// ============================================================================
// WebSocket Types
// ============================================================================

/** WebSocket message payload */
export interface WebSocketMessage {
  /** Event type */
  event: string;
  /** Message data */
  data: Record<string, unknown>;
  /** Channel name */
  channel?: string;
  /** Symbol */
  symbol?: string;
}

/** Stock WebSocket channel types */
export type StockChannel = 'trades' | 'books' | 'candles' | 'aggregates' | 'indices';

/** FutOpt WebSocket channel types */
export type FutOptChannel = 'trades' | 'books' | 'candles' | 'aggregates';

/**
 * Subscribe options for stock WebSocket
 */
export interface StockSubscribeOptions {
  /** Channel to subscribe to */
  channel: StockChannel;
  /** Stock symbol */
  symbol: string;
  /** Include intraday odd lot data */
  intradayOddLot?: boolean;
}

/**
 * Subscribe options for FutOpt WebSocket
 */
export interface FutOptSubscribeOptions {
  /** Channel to subscribe to */
  channel: FutOptChannel;
  /** Contract symbol */
  symbol: string;
  /** Include after-hours data */
  afterHours?: boolean;
}

/**
 * Event map for typed WebSocket callbacks
 */
export interface WebSocketEventMap {
  /** Market data message received */
  message: (data: string) => void;
  /** Connected to WebSocket server */
  connect: (info: string) => void;
  /** Disconnected from WebSocket server */
  disconnect: (reason: string) => void;
  /** Reconnecting to WebSocket server */
  reconnect: (info: string) => void;
  /** Error occurred */
  error: (error: string) => void;
}

/** Event names for WebSocket */
export type WebSocketEvent = keyof WebSocketEventMap;

// ============================================================================
// Client Classes
// ============================================================================

/** Futures and Options market data client */
export declare class FutOptClient {
  /** Get intraday client for real-time futures/options data */
  get intraday(): FutOptIntradayClient
}

/** FutOpt intraday data client */
export declare class FutOptIntradayClient {
  /**
   * Get intraday quote for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4" for TX futures, "TXO18000C4" for options)
   * @returns Promise resolving to Quote object with current price and volume data
   *
   * @example
   * ```javascript
   * const client = new RestClient('your-api-key');
   * const quote = await client.futopt.intraday.quote('TXFC4');
   * console.log(quote.lastPrice);  // 17550.0
   * console.log(quote.symbol);     // "TXFC4"
   * ```
   */
  quote(symbol: string): Promise<QuoteResponse>

  /**
   * Get intraday ticker for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4")
   * @returns Promise resolving to Ticker object with contract info
   */
  ticker(symbol: string): Promise<TickerResponse>

  /**
   * Get intraday candles for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4")
   * @param timeframe - Candle timeframe: "1", "5", "10", "15", "30", "60" (minutes)
   * @returns Promise resolving to Candles response with OHLCV data
   */
  candles(symbol: string, timeframe: string): Promise<CandlesResponse>

  /**
   * Get intraday trades for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4")
   * @returns Promise resolving to Trades response with recent trade history
   */
  trades(symbol: string): Promise<TradesResponse>

  /**
   * Get intraday volumes for a futures/options contract
   *
   * @param symbol - Contract symbol (e.g., "TXFC4")
   * @returns Promise resolving to Volumes response with volume at each price level
   */
  volumes(symbol: string): Promise<VolumesResponse>

  /**
   * Get product list for futures/options
   *
   * @param type - Type: "FUTURE" or "OPTION" (required)
   * @param contractType - Contract type filter (optional): "I" (index), "R" (rate), "B" (bond), "C" (currency), "S" (stock), "E" (ETF)
   * @returns Promise resolving to Products response with available contracts
   */
  products(type: FutOptType, contractType?: ContractType): Promise<ProductsResponse>
}

/**
 * FutOpt WebSocket client for real-time futures/options market data
 *
 * @example
 * ```javascript
 * // Event handlers
 * ws.futopt.on('message', (data) => {
 *   const msg = JSON.parse(data);
 *   console.log(msg);
 * });
 * ws.futopt.on('connect', () => console.log('FutOpt WebSocket connected'));
 *
 * // Connect
 * ws.futopt.connect();
 *
 * // Subscribe to channels
 * ws.futopt.subscribe({ channel: 'trades', symbol: 'TXFC4' });
 * ws.futopt.subscribe({ channel: 'books', symbol: 'MXFB4', afterHours: true });
 * ```
 */
export declare class FutOptWebSocketClient {
  /**
   * Register an event handler
   *
   * @param event - Event type: "message", "connect", "disconnect", "reconnect", "error"
   * @param callback - Callback function receiving event data
   */
  on<K extends WebSocketEvent>(event: K, callback: WebSocketEventMap[K]): void

  /**
   * Connect to the FutOpt WebSocket server
   *
   * This method spawns a background thread that manages the WebSocket connection.
   * Connection result will be delivered via 'connect' or 'error' callbacks.
   */
  connect(): void

  /**
   * Subscribe to a channel
   *
   * @param options - Subscription options with channel and symbol
   */
  subscribe(options: FutOptSubscribeOptions): void

  /**
   * Unsubscribe from a channel by subscription ID
   *
   * @param subscriptionId - The subscription ID returned from subscribed event
   */
  unsubscribe(subscriptionId: string): void

  /** Disconnect from the WebSocket server */
  disconnect(): void

  /** Check if connected */
  get isConnected(): boolean

  /**
   * Check if client has been closed
   *
   * Returns true if disconnect() has been called and client is closed.
   * Once closed, the client cannot be reused - create a new instance.
   */
  get isClosed(): boolean
}

/**
 * REST client for Fugle market data API (JavaScript wrapper)
 *
 * @example
 * ```javascript
 * const { RestClient } = require('@fugle/marketdata');
 *
 * // Create client with API key
 * const client = new RestClient('your-api-key');
 *
 * // Access stock market data
 * const quote = await client.stock.intraday.quote('2330');
 * console.log(quote.lastPrice, quote.symbol);
 *
 * // Access futures/options market data
 * const futoptQuote = await client.futopt.intraday.quote('TXFC4');
 * console.log(futoptQuote.lastPrice, futoptQuote.symbol);
 * ```
 */
export declare class RestClient {
  /**
   * Create a new REST client with API key authentication
   *
   * @param apiKey - Your Fugle API key
   */
  constructor(apiKey: string)

  /** Get the stock client for accessing stock market data */
  get stock(): StockClient

  /** Get the FutOpt client for accessing futures/options market data */
  get futopt(): FutOptClient
}

/** Stock market data client */
export declare class StockClient {
  /** Get intraday client for real-time stock data */
  get intraday(): StockIntradayClient
}

/** Stock intraday data client */
export declare class StockIntradayClient {
  /**
   * Get intraday quote for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @returns Promise resolving to Quote object with current price and volume data
   *
   * @example
   * ```javascript
   * const client = new RestClient('your-api-key');
   * const quote = await client.stock.intraday.quote('2330');
   * console.log(quote.lastPrice);  // 580.0
   * console.log(quote.symbol);     // "2330"
   * console.log(quote.bids);       // [{price: 579.0, size: 100}, ...]
   * ```
   */
  quote(symbol: string): Promise<QuoteResponse>

  /**
   * Get intraday ticker for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @returns Promise resolving to Ticker object with security info
   */
  ticker(symbol: string): Promise<TickerResponse>

  /**
   * Get intraday candles for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @param timeframe - Candle timeframe: "1", "5", "10", "15", "30", "60" (minutes)
   * @returns Promise resolving to Candles response with OHLCV data
   */
  candles(symbol: string, timeframe: string): Promise<CandlesResponse>

  /**
   * Get intraday trades for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @returns Promise resolving to Trades response with recent trade history
   */
  trades(symbol: string): Promise<TradesResponse>

  /**
   * Get intraday volumes for a stock symbol
   *
   * @param symbol - Stock symbol (e.g., "2330" for TSMC)
   * @returns Promise resolving to Volumes response with volume at each price level
   */
  volumes(symbol: string): Promise<VolumesResponse>
}

/**
 * Stock WebSocket client for real-time stock market data
 *
 * @example
 * ```javascript
 * // Event handlers
 * ws.stock.on('message', (data) => {
 *   const msg = JSON.parse(data);
 *   console.log(msg);
 * });
 * ws.stock.on('connect', () => console.log('Stock WebSocket connected'));
 * ws.stock.on('disconnect', (reason) => console.log('Disconnected:', reason));
 * ws.stock.on('reconnect', (info) => console.log('Reconnecting:', info));
 * ws.stock.on('error', (err) => console.error('Error:', err));
 *
 * // Connect
 * ws.stock.connect();
 *
 * // Subscribe to channels
 * ws.stock.subscribe({ channel: 'trades', symbol: '2330' });
 * ws.stock.subscribe({ channel: 'candles', symbol: '2330' });
 * ```
 */
export declare class StockWebSocketClient {
  /**
   * Register an event handler
   *
   * @param event - Event type: "message", "connect", "disconnect", "reconnect", "error"
   * @param callback - Callback function receiving event data
   *
   * @example
   * ```javascript
   * ws.stock.on('message', (data) => console.log(data));
   * ws.stock.on('connect', () => console.log('Connected'));
   * ws.stock.on('error', (err) => console.error(err));
   * ```
   */
  on<K extends WebSocketEvent>(event: K, callback: WebSocketEventMap[K]): void

  /**
   * Connect to the stock WebSocket server
   *
   * This method spawns a background thread that manages the WebSocket connection.
   * Connection result will be delivered via 'connect' or 'error' callbacks.
   */
  connect(): void

  /**
   * Subscribe to a channel
   *
   * @param options - Subscription options with channel and symbol
   */
  subscribe(options: StockSubscribeOptions): void

  /**
   * Unsubscribe from a channel by subscription ID
   *
   * @param subscriptionId - The subscription ID returned from subscribed event
   */
  unsubscribe(subscriptionId: string): void

  /** Disconnect from the WebSocket server */
  disconnect(): void

  /** Check if connected */
  get isConnected(): boolean

  /**
   * Check if client has been closed
   *
   * Returns true if disconnect() has been called and client is closed.
   * Once closed, the client cannot be reused - create a new instance.
   */
  get isClosed(): boolean
}

/**
 * WebSocket client for real-time market data (JavaScript wrapper)
 *
 * @example
 * ```javascript
 * const { WebSocketClient } = require('@fugle/marketdata');
 *
 * // Create client with API key
 * const ws = new WebSocketClient('your-api-key');
 *
 * // Register event handlers for stock data
 * ws.stock.on('message', (data) => console.log(JSON.parse(data)));
 * ws.stock.on('connect', () => console.log('Connected!'));
 * ws.stock.on('error', (err) => console.error(err));
 *
 * // Connect and subscribe
 * ws.stock.connect();
 * ws.stock.subscribe({ channel: 'trades', symbol: '2330' });
 * ```
 */
export declare class WebSocketClient {
  /**
   * Create a new WebSocket client with API key authentication
   *
   * @param apiKey - Your Fugle API key
   */
  constructor(apiKey: string)

  /** Get the stock WebSocket client for real-time stock data */
  get stock(): StockWebSocketClient

  /** Get the FutOpt WebSocket client for real-time futures/options data */
  get futopt(): FutOptWebSocketClient
}
