

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER_METHOD0
typedef void (*UniffiCallbackInterfaceWebSocketListenerMethod0)(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceWebSocketListenerMethod0(
				UniffiCallbackInterfaceWebSocketListenerMethod0 cb, uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER_METHOD1
typedef void (*UniffiCallbackInterfaceWebSocketListenerMethod1)(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceWebSocketListenerMethod1(
				UniffiCallbackInterfaceWebSocketListenerMethod1 cb, uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER_METHOD2
typedef void (*UniffiCallbackInterfaceWebSocketListenerMethod2)(uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceWebSocketListenerMethod2(
				UniffiCallbackInterfaceWebSocketListenerMethod2 cb, uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, message, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER_METHOD3
typedef void (*UniffiCallbackInterfaceWebSocketListenerMethod3)(uint64_t uniffi_handle, RustBuffer error_message, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceWebSocketListenerMethod3(
				UniffiCallbackInterfaceWebSocketListenerMethod3 cb, uint64_t uniffi_handle, RustBuffer error_message, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, error_message, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_WEB_SOCKET_LISTENER
typedef struct UniffiVTableCallbackInterfaceWebSocketListener {
    UniffiCallbackInterfaceWebSocketListenerMethod0 onConnected;
    UniffiCallbackInterfaceWebSocketListenerMethod1 onDisconnected;
    UniffiCallbackInterfaceWebSocketListenerMethod2 onMessage;
    UniffiCallbackInterfaceWebSocketListenerMethod3 onError;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceWebSocketListener;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_FUTOPTCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_FUTOPTCLIENT
void* uniffi_marketdata_uniffi_fn_clone_futoptclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_FUTOPTCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_FUTOPTCLIENT
void uniffi_marketdata_uniffi_fn_free_futoptclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTCLIENT_INTRADAY
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTCLIENT_INTRADAY
void* uniffi_marketdata_uniffi_fn_method_futoptclient_intraday(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_FUTOPTINTRADAYCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_FUTOPTINTRADAYCLIENT
void* uniffi_marketdata_uniffi_fn_clone_futoptintradayclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_FUTOPTINTRADAYCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_FUTOPTINTRADAYCLIENT
void uniffi_marketdata_uniffi_fn_free_futoptintradayclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_GET_PRODUCTS
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_GET_PRODUCTS
uint64_t uniffi_marketdata_uniffi_fn_method_futoptintradayclient_get_products(void* ptr, RustBuffer typ
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_GET_QUOTE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_GET_QUOTE
uint64_t uniffi_marketdata_uniffi_fn_method_futoptintradayclient_get_quote(void* ptr, RustBuffer symbol, int8_t after_hours
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_GET_TICKER
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_GET_TICKER
uint64_t uniffi_marketdata_uniffi_fn_method_futoptintradayclient_get_ticker(void* ptr, RustBuffer symbol, int8_t after_hours
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_PRODUCTS_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_PRODUCTS_SYNC
RustBuffer uniffi_marketdata_uniffi_fn_method_futoptintradayclient_products_sync(void* ptr, RustBuffer typ, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_QUOTE_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_QUOTE_SYNC
RustBuffer uniffi_marketdata_uniffi_fn_method_futoptintradayclient_quote_sync(void* ptr, RustBuffer symbol, int8_t after_hours, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_TICKER_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_FUTOPTINTRADAYCLIENT_TICKER_SYNC
RustBuffer uniffi_marketdata_uniffi_fn_method_futoptintradayclient_ticker_sync(void* ptr, RustBuffer symbol, int8_t after_hours, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_RESTCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_RESTCLIENT
void* uniffi_marketdata_uniffi_fn_clone_restclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_RESTCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_RESTCLIENT
void uniffi_marketdata_uniffi_fn_free_restclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_RESTCLIENT_FUTOPT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_RESTCLIENT_FUTOPT
void* uniffi_marketdata_uniffi_fn_method_restclient_futopt(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_RESTCLIENT_STOCK
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_RESTCLIENT_STOCK
void* uniffi_marketdata_uniffi_fn_method_restclient_stock(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_STOCKCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_STOCKCLIENT
void* uniffi_marketdata_uniffi_fn_clone_stockclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_STOCKCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_STOCKCLIENT
void uniffi_marketdata_uniffi_fn_free_stockclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKCLIENT_INTRADAY
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKCLIENT_INTRADAY
void* uniffi_marketdata_uniffi_fn_method_stockclient_intraday(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_STOCKINTRADAYCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_STOCKINTRADAYCLIENT
void* uniffi_marketdata_uniffi_fn_clone_stockintradayclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_STOCKINTRADAYCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_STOCKINTRADAYCLIENT
void uniffi_marketdata_uniffi_fn_free_stockintradayclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_CANDLES_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_CANDLES_SYNC
RustBuffer uniffi_marketdata_uniffi_fn_method_stockintradayclient_candles_sync(void* ptr, RustBuffer symbol, RustBuffer timeframe, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_CANDLES
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_CANDLES
uint64_t uniffi_marketdata_uniffi_fn_method_stockintradayclient_get_candles(void* ptr, RustBuffer symbol, RustBuffer timeframe
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_QUOTE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_QUOTE
uint64_t uniffi_marketdata_uniffi_fn_method_stockintradayclient_get_quote(void* ptr, RustBuffer symbol
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_TICKER
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_TICKER
uint64_t uniffi_marketdata_uniffi_fn_method_stockintradayclient_get_ticker(void* ptr, RustBuffer symbol
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_TRADES
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_TRADES
uint64_t uniffi_marketdata_uniffi_fn_method_stockintradayclient_get_trades(void* ptr, RustBuffer symbol
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_VOLUMES
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_GET_VOLUMES
uint64_t uniffi_marketdata_uniffi_fn_method_stockintradayclient_get_volumes(void* ptr, RustBuffer symbol
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_QUOTE_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_QUOTE_SYNC
RustBuffer uniffi_marketdata_uniffi_fn_method_stockintradayclient_quote_sync(void* ptr, RustBuffer symbol, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_TICKER_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_TICKER_SYNC
RustBuffer uniffi_marketdata_uniffi_fn_method_stockintradayclient_ticker_sync(void* ptr, RustBuffer symbol, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_TRADES_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_TRADES_SYNC
RustBuffer uniffi_marketdata_uniffi_fn_method_stockintradayclient_trades_sync(void* ptr, RustBuffer symbol, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_VOLUMES_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_STOCKINTRADAYCLIENT_VOLUMES_SYNC
RustBuffer uniffi_marketdata_uniffi_fn_method_stockintradayclient_volumes_sync(void* ptr, RustBuffer symbol, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_WEBSOCKETCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_WEBSOCKETCLIENT
void* uniffi_marketdata_uniffi_fn_clone_websocketclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_WEBSOCKETCLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_WEBSOCKETCLIENT
void uniffi_marketdata_uniffi_fn_free_websocketclient(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CONSTRUCTOR_WEBSOCKETCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CONSTRUCTOR_WEBSOCKETCLIENT_NEW
void* uniffi_marketdata_uniffi_fn_constructor_websocketclient_new(RustBuffer api_key, void* listener, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CONSTRUCTOR_WEBSOCKETCLIENT_NEW_WITH_ENDPOINT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CONSTRUCTOR_WEBSOCKETCLIENT_NEW_WITH_ENDPOINT
void* uniffi_marketdata_uniffi_fn_constructor_websocketclient_new_with_endpoint(RustBuffer api_key, void* listener, RustBuffer endpoint, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_CONNECT
uint64_t uniffi_marketdata_uniffi_fn_method_websocketclient_connect(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_DISCONNECT
uint64_t uniffi_marketdata_uniffi_fn_method_websocketclient_disconnect(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_IS_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_IS_CONNECTED
int8_t uniffi_marketdata_uniffi_fn_method_websocketclient_is_connected(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_SUBSCRIBE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_SUBSCRIBE
uint64_t uniffi_marketdata_uniffi_fn_method_websocketclient_subscribe(void* ptr, RustBuffer channel, RustBuffer symbol
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_UNSUBSCRIBE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETCLIENT_UNSUBSCRIBE
uint64_t uniffi_marketdata_uniffi_fn_method_websocketclient_unsubscribe(void* ptr, RustBuffer channel, RustBuffer symbol
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_WEBSOCKETLISTENER
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_CLONE_WEBSOCKETLISTENER
void* uniffi_marketdata_uniffi_fn_clone_websocketlistener(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_WEBSOCKETLISTENER
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FREE_WEBSOCKETLISTENER
void uniffi_marketdata_uniffi_fn_free_websocketlistener(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_INIT_CALLBACK_VTABLE_WEBSOCKETLISTENER
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_INIT_CALLBACK_VTABLE_WEBSOCKETLISTENER
void uniffi_marketdata_uniffi_fn_init_callback_vtable_websocketlistener(UniffiVTableCallbackInterfaceWebSocketListener* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETLISTENER_ON_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETLISTENER_ON_CONNECTED
void uniffi_marketdata_uniffi_fn_method_websocketlistener_on_connected(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETLISTENER_ON_DISCONNECTED
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETLISTENER_ON_DISCONNECTED
void uniffi_marketdata_uniffi_fn_method_websocketlistener_on_disconnected(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETLISTENER_ON_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETLISTENER_ON_MESSAGE
void uniffi_marketdata_uniffi_fn_method_websocketlistener_on_message(void* ptr, RustBuffer message, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETLISTENER_ON_ERROR
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_METHOD_WEBSOCKETLISTENER_ON_ERROR
void uniffi_marketdata_uniffi_fn_method_websocketlistener_on_error(void* ptr, RustBuffer error_message, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_REST_CLIENT_WITH_API_KEY
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_REST_CLIENT_WITH_API_KEY
void* uniffi_marketdata_uniffi_fn_func_new_rest_client_with_api_key(RustBuffer api_key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_REST_CLIENT_WITH_BEARER_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_REST_CLIENT_WITH_BEARER_TOKEN
void* uniffi_marketdata_uniffi_fn_func_new_rest_client_with_bearer_token(RustBuffer bearer_token, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_REST_CLIENT_WITH_SDK_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_REST_CLIENT_WITH_SDK_TOKEN
void* uniffi_marketdata_uniffi_fn_func_new_rest_client_with_sdk_token(RustBuffer sdk_token, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_WEBSOCKET_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_WEBSOCKET_CLIENT
void* uniffi_marketdata_uniffi_fn_func_new_websocket_client(RustBuffer api_key, void* listener, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_WEBSOCKET_CLIENT_WITH_ENDPOINT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_FN_FUNC_NEW_WEBSOCKET_CLIENT_WITH_ENDPOINT
void* uniffi_marketdata_uniffi_fn_func_new_websocket_client_with_endpoint(RustBuffer api_key, void* listener, RustBuffer endpoint, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUSTBUFFER_ALLOC
RustBuffer ffi_marketdata_uniffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_marketdata_uniffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUSTBUFFER_FREE
void ffi_marketdata_uniffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUSTBUFFER_RESERVE
RustBuffer ffi_marketdata_uniffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_U8
void ffi_marketdata_uniffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_U8
void ffi_marketdata_uniffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_U8
void ffi_marketdata_uniffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_marketdata_uniffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_I8
void ffi_marketdata_uniffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_I8
void ffi_marketdata_uniffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_I8
void ffi_marketdata_uniffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_marketdata_uniffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_U16
void ffi_marketdata_uniffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_U16
void ffi_marketdata_uniffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_U16
void ffi_marketdata_uniffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_marketdata_uniffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_I16
void ffi_marketdata_uniffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_I16
void ffi_marketdata_uniffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_I16
void ffi_marketdata_uniffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_marketdata_uniffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_U32
void ffi_marketdata_uniffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_U32
void ffi_marketdata_uniffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_U32
void ffi_marketdata_uniffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_marketdata_uniffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_I32
void ffi_marketdata_uniffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_I32
void ffi_marketdata_uniffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_I32
void ffi_marketdata_uniffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_marketdata_uniffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_U64
void ffi_marketdata_uniffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_U64
void ffi_marketdata_uniffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_U64
void ffi_marketdata_uniffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_marketdata_uniffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_I64
void ffi_marketdata_uniffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_I64
void ffi_marketdata_uniffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_I64
void ffi_marketdata_uniffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_marketdata_uniffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_F32
void ffi_marketdata_uniffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_F32
void ffi_marketdata_uniffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_F32
void ffi_marketdata_uniffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_F32
float ffi_marketdata_uniffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_F64
void ffi_marketdata_uniffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_F64
void ffi_marketdata_uniffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_F64
void ffi_marketdata_uniffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_F64
double ffi_marketdata_uniffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_POINTER
void ffi_marketdata_uniffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_POINTER
void ffi_marketdata_uniffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_POINTER
void ffi_marketdata_uniffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_POINTER
void* ffi_marketdata_uniffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_marketdata_uniffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_marketdata_uniffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_marketdata_uniffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_marketdata_uniffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_POLL_VOID
void ffi_marketdata_uniffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_CANCEL_VOID
void ffi_marketdata_uniffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_FREE_VOID
void ffi_marketdata_uniffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_RUST_FUTURE_COMPLETE_VOID
void ffi_marketdata_uniffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_REST_CLIENT_WITH_API_KEY
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_REST_CLIENT_WITH_API_KEY
uint16_t uniffi_marketdata_uniffi_checksum_func_new_rest_client_with_api_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_REST_CLIENT_WITH_BEARER_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_REST_CLIENT_WITH_BEARER_TOKEN
uint16_t uniffi_marketdata_uniffi_checksum_func_new_rest_client_with_bearer_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_REST_CLIENT_WITH_SDK_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_REST_CLIENT_WITH_SDK_TOKEN
uint16_t uniffi_marketdata_uniffi_checksum_func_new_rest_client_with_sdk_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_WEBSOCKET_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_WEBSOCKET_CLIENT
uint16_t uniffi_marketdata_uniffi_checksum_func_new_websocket_client(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_WEBSOCKET_CLIENT_WITH_ENDPOINT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_FUNC_NEW_WEBSOCKET_CLIENT_WITH_ENDPOINT
uint16_t uniffi_marketdata_uniffi_checksum_func_new_websocket_client_with_endpoint(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTCLIENT_INTRADAY
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTCLIENT_INTRADAY
uint16_t uniffi_marketdata_uniffi_checksum_method_futoptclient_intraday(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_GET_PRODUCTS
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_GET_PRODUCTS
uint16_t uniffi_marketdata_uniffi_checksum_method_futoptintradayclient_get_products(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_GET_QUOTE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_GET_QUOTE
uint16_t uniffi_marketdata_uniffi_checksum_method_futoptintradayclient_get_quote(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_GET_TICKER
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_GET_TICKER
uint16_t uniffi_marketdata_uniffi_checksum_method_futoptintradayclient_get_ticker(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_PRODUCTS_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_PRODUCTS_SYNC
uint16_t uniffi_marketdata_uniffi_checksum_method_futoptintradayclient_products_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_QUOTE_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_QUOTE_SYNC
uint16_t uniffi_marketdata_uniffi_checksum_method_futoptintradayclient_quote_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_TICKER_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_FUTOPTINTRADAYCLIENT_TICKER_SYNC
uint16_t uniffi_marketdata_uniffi_checksum_method_futoptintradayclient_ticker_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_RESTCLIENT_FUTOPT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_RESTCLIENT_FUTOPT
uint16_t uniffi_marketdata_uniffi_checksum_method_restclient_futopt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_RESTCLIENT_STOCK
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_RESTCLIENT_STOCK
uint16_t uniffi_marketdata_uniffi_checksum_method_restclient_stock(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKCLIENT_INTRADAY
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKCLIENT_INTRADAY
uint16_t uniffi_marketdata_uniffi_checksum_method_stockclient_intraday(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_CANDLES_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_CANDLES_SYNC
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_candles_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_CANDLES
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_CANDLES
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_get_candles(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_QUOTE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_QUOTE
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_get_quote(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_TICKER
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_TICKER
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_get_ticker(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_TRADES
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_TRADES
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_get_trades(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_VOLUMES
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_GET_VOLUMES
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_get_volumes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_QUOTE_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_QUOTE_SYNC
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_quote_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_TICKER_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_TICKER_SYNC
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_ticker_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_TRADES_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_TRADES_SYNC
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_trades_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_VOLUMES_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_STOCKINTRADAYCLIENT_VOLUMES_SYNC
uint16_t uniffi_marketdata_uniffi_checksum_method_stockintradayclient_volumes_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_CONNECT
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketclient_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_DISCONNECT
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketclient_disconnect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_IS_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_IS_CONNECTED
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketclient_is_connected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_SUBSCRIBE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_SUBSCRIBE
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketclient_subscribe(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_UNSUBSCRIBE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETCLIENT_UNSUBSCRIBE
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketclient_unsubscribe(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETLISTENER_ON_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETLISTENER_ON_CONNECTED
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketlistener_on_connected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETLISTENER_ON_DISCONNECTED
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETLISTENER_ON_DISCONNECTED
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketlistener_on_disconnected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETLISTENER_ON_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETLISTENER_ON_MESSAGE
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketlistener_on_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETLISTENER_ON_ERROR
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_METHOD_WEBSOCKETLISTENER_ON_ERROR
uint16_t uniffi_marketdata_uniffi_checksum_method_websocketlistener_on_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_CONSTRUCTOR_WEBSOCKETCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_CONSTRUCTOR_WEBSOCKETCLIENT_NEW
uint16_t uniffi_marketdata_uniffi_checksum_constructor_websocketclient_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_CONSTRUCTOR_WEBSOCKETCLIENT_NEW_WITH_ENDPOINT
#define UNIFFI_FFIDEF_UNIFFI_MARKETDATA_UNIFFI_CHECKSUM_CONSTRUCTOR_WEBSOCKETCLIENT_NEW_WITH_ENDPOINT
uint16_t uniffi_marketdata_uniffi_checksum_constructor_websocketclient_new_with_endpoint(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_MARKETDATA_UNIFFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_marketdata_uniffi_uniffi_contract_version(void
    
);
#endif

 void marketdata_uniffi_cgo_dispatchCallbackInterfaceWebSocketListenerMethod0(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );
 void marketdata_uniffi_cgo_dispatchCallbackInterfaceWebSocketListenerMethod1(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );
 void marketdata_uniffi_cgo_dispatchCallbackInterfaceWebSocketListenerMethod2(uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus );
 void marketdata_uniffi_cgo_dispatchCallbackInterfaceWebSocketListenerMethod3(uint64_t uniffi_handle, RustBuffer error_message, void* uniffi_out_return, RustCallStatus* callStatus );
 void marketdata_uniffi_cgo_dispatchCallbackInterfaceWebSocketListenerFree(uint64_t handle);

void marketdata_uniffi_uniffiFutureContinuationCallback(uint64_t, int8_t);
void marketdata_uniffi_uniffiFreeGorutine(uint64_t);
