// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Fugle.MarketData.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "fugle_marketdata";





        /// <summary>
        ///  Get library version (stub for csbindgen to generate bindings)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* fugle_version();

        /// <summary>
        ///  Free a string allocated by Rust (for C# to call)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_free_string(byte* ptr);

        /// <summary>
        ///  Create a new REST client with API key
        ///  Returns: client handle pointer, or null on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_client_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern RestClientHandle* fugle_rest_client_new(byte* api_key);

        /// <summary>
        ///  Destroy a REST client handle
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_client_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_client_free(RestClientHandle* handle);

        /// <summary>
        ///  Get intraday quote for a stock symbol (async)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_stock_quote_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_stock_quote_async(RestClientHandle* handle, byte* symbol, delegate* unmanaged[Cdecl]<void*, byte*, int, void> callback, void* user_data);

        /// <summary>
        ///  Get intraday trades for a stock symbol (async)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_stock_trades_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_stock_trades_async(RestClientHandle* handle, byte* symbol, delegate* unmanaged[Cdecl]<void*, byte*, int, void> callback, void* user_data);

        /// <summary>
        ///  Get intraday ticker info for a stock symbol (async)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_stock_ticker_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_stock_ticker_async(RestClientHandle* handle, byte* symbol, delegate* unmanaged[Cdecl]<void*, byte*, int, void> callback, void* user_data);

        /// <summary>
        ///  Get intraday candles for a stock symbol (async)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_stock_candles_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_stock_candles_async(RestClientHandle* handle, byte* symbol, delegate* unmanaged[Cdecl]<void*, byte*, int, void> callback, void* user_data);

        /// <summary>
        ///  Get intraday volumes for a stock symbol (async)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_stock_volumes_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_stock_volumes_async(RestClientHandle* handle, byte* symbol, delegate* unmanaged[Cdecl]<void*, byte*, int, void> callback, void* user_data);

        /// <summary>
        ///  Get intraday quote for a FutOpt contract (async)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_futopt_quote_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_futopt_quote_async(RestClientHandle* handle, byte* symbol, delegate* unmanaged[Cdecl]<void*, byte*, int, void> callback, void* user_data);

        /// <summary>
        ///  Get intraday ticker info for a FutOpt contract (async)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_futopt_ticker_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_futopt_ticker_async(RestClientHandle* handle, byte* symbol, delegate* unmanaged[Cdecl]<void*, byte*, int, void> callback, void* user_data);

        /// <summary>
        ///  Get available FutOpt products (async)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_rest_futopt_products_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_rest_futopt_products_async(RestClientHandle* handle, delegate* unmanaged[Cdecl]<void*, byte*, int, void> callback, void* user_data);

        /// <summary>
        ///  Create a new WebSocket client with API key
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_ws_client_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern WebSocketHandle* fugle_ws_client_new(byte* _api_key);

        /// <summary>
        ///  Connect WebSocket client (blocking during handshake)
        ///  endpoint_type: 0 = stock, 1 = futopt
        ///  Returns: SUCCESS on success, error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_ws_connect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int fugle_ws_connect(WebSocketHandle* handle, byte* api_key, int endpoint_type);

        /// <summary>
        ///  Disconnect WebSocket client
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_ws_disconnect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int fugle_ws_disconnect(WebSocketHandle* handle);

        /// <summary>
        ///  Get current connection state
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_ws_get_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int fugle_ws_get_state(WebSocketHandle* handle);

        /// <summary>
        ///  Poll for next message (non-blocking)
        ///  Returns: MESSAGE_AVAILABLE if message retrieved, NO_MESSAGE if none, error code on failure
        ///  On MESSAGE_AVAILABLE, message_out is set to JSON string (caller must free with fugle_free_string)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_ws_poll_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int fugle_ws_poll_message(WebSocketHandle* handle, byte** message_out);

        /// <summary>
        ///  Subscribe to a channel
        ///  channel: "trades", "books", "candles", etc.
        ///  symbol: stock/futopt symbol like "2330" or "TXFF4"
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_ws_subscribe", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int fugle_ws_subscribe(WebSocketHandle* handle, byte* channel, byte* symbol);

        /// <summary>
        ///  Unsubscribe from a channel
        ///  key: subscription key in format "channel:symbol" (e.g., "trades:2330")
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_ws_unsubscribe", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int fugle_ws_unsubscribe(WebSocketHandle* handle, byte* key);

        /// <summary>
        ///  Destroy WebSocket client handle
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fugle_ws_client_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fugle_ws_client_free(WebSocketHandle* handle);


    }

    /// <summary>
    ///  Opaque handle for REST client
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct RestClientHandle
    {
    }

    /// <summary>
    ///  Opaque handle for WebSocket client
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct WebSocketHandle
    {
    }



}
